[package]
name = "procem_default"
version = "0.2.0"
edition = "2024"

[dependencies]
procem = { path = "../procem", features = ["alloc"] }
thiserror = { workspace = true }
ars = {workspace= true, features= ["alloc"]}

[lib]
name = "procem_default"

[dev-dependencies]
criterion = "0.8.2"
dev_utilities = { path = "../dev_utilities" }

[[bench]]
name = "tokenizer"
harness = false

[[bench]]
name = "tokenizer_perf"
harness = false
