[package]
name = "procasm"
version = "0.2.0"
edition = "2024"
repository = "https://github.com/A1cey/procem/tree/main/procasm"
license = "MIT"
description = "procasm is the default implementation of an instruction set for the procem library"
keywords = ["processor", "emulator", "simulator", "cpu", "procem"]

[dependencies]
procem = { path = "../procem", features = ["alloc"], version = "0.2.0" }
thiserror = { workspace = true }
ars = {workspace= true, features= ["alloc"]}

[lib]
name = "procasm"

[dev-dependencies]
criterion = "0.8.2"
dev_utilities = { path = "../dev_utilities" }
pretty_assertions_sorted = "1.2.3"

[[bench]]
name = "tokenizer"
harness = false

[[bench]]
name = "tokenizer_perf"
harness = false
